export enum ResponseMessages {
  SUCCESS = 'Request completed successfully.',
  CREATED = 'Resource created successfully.',
  UPDATED = 'Resource updated successfully.',
  DELETED = 'Resource deleted successfully.',
  NOT_FOUND = 'Resource not found.',
  BAD_REQUEST = 'Invalid request data.',
  UNAUTHORIZED = 'Authentication required.',
  FORBIDDEN = 'You do not have permission to access this resource.',
  INTERNAL_SERVER_ERROR = 'An unexpected error occurred.',
  CONFLICT = 'Resource already exists.',
  VALIDATION_FAILED = 'Validation failed for one or more fields.',
  INVALID_EMAIL = 'Invalid email address.',
  INVALID_CREDENTIALS = 'Email or password is incorrect.',
  TOKEN_EXPIRED = 'Token has expired.',
  TOKEN_INVALID = 'Token is invalid.',
  LOGIN_SUCCESS = 'Logged in successfully.',
  LOGOUT_SUCCESS = 'Logged out successfully.',
  USER_REGISTERED = 'User registered successfully.',
  ACCESS_DENIED = 'Access denied.',
  EMAIL_ALREADY_EXISTS = 'Email is already registered.',
  USER_NOT_FOUND = 'User not found.',
  PASSWORD_INCORRECT = 'Incorrect password.',
}
